function cfg = pipeline_config(varargin)
%PIPELINE_CONFIG Central paths and run settings for the HD/AHV pipeline.
%
% Edit DataRoot below, or override it without editing this file:
%   cfg = pipeline_config('DataRoot', '/path/to/data');
%
% DataRoot must contain the morph folders surface/, molino/ and pachon/.

pipelineRoot = fileparts(fileparts(mfilename('fullpath')));

p = inputParser;
p.FunctionName = mfilename;
addParameter(p, 'DataRoot', '/home/blanche/data', ...
    @(x) ischar(x) || (isstring(x) && isscalar(x)));
addParameter(p, 'PipelineRoot', pipelineRoot, ...
    @(x) ischar(x) || (isstring(x) && isscalar(x)));
addParameter(p, 'FigureVisible', 'off', ...
    @(x) any(strcmpi(string(x), ["on","off"])));
addParameter(p, 'OverwriteOutputs', true, ...
    @(x) islogical(x) || (isnumeric(x) && isscalar(x)));
addParameter(p, 'ForceModelRefit', false, ...
    @(x) islogical(x) || (isnumeric(x) && isscalar(x)));
parse(p, varargin{:});

cfg = p.Results;
cfg.DataRoot = char(cfg.DataRoot);
cfg.PipelineRoot = char(cfg.PipelineRoot);
cfg.FigureVisible = char(cfg.FigureVisible);
cfg.OverwriteOutputs = logical(cfg.OverwriteOutputs);
cfg.ForceModelRefit = logical(cfg.ForceModelRefit);

cfg.Morphs = struct( ...
    'name', {'surface','molino','pachon'}, ...
    'display', {'Surface','Molino','Pachon'});
for i = 1:numel(cfg.Morphs)
    cfg.Morphs(i).dataDir = fullfile(cfg.DataRoot, cfg.Morphs(i).name);
end

cfg.DataProcessedDir = fullfile(cfg.PipelineRoot, 'data_processed');
cfg.OutputsDir = fullfile(cfg.PipelineRoot, 'outputs');

cfg.ModelDataDir = fullfile(cfg.DataProcessedDir, 'model_fits');
cfg.SessionModelDataDir = fullfile(cfg.ModelDataDir, 'sessions');
cfg.ClassifiedCandidateDir = ...
    fullfile(cfg.DataProcessedDir, 'classified_candidates');

cfg.ModelFigureDir = fullfile(cfg.OutputsDir, 'model_fits');
cfg.ModelComparisonDir = fullfile(cfg.OutputsDir, 'model_comparison');
cfg.AnatomyComparisonDir = fullfile(cfg.OutputsDir, 'anatomy_comparison');
cfg.PosterFigureDir = fullfile(cfg.OutputsDir, 'poster_figures');
cfg.ClassComparisonDir = fullfile(cfg.OutputsDir, ...
    'class_comparison_functional');

% The anatomy analysis uses the coordinate-rich model generated by the
% pre-existing anatomy/model workflow. These are read-only inputs.
for i = 1:numel(cfg.Morphs)
    cfg.Morphs(i).anatomyModelFile = fullfile( ...
        cfg.Morphs(i).dataDir, ...
        'HD_AHV_neuron_model_outputs_candidate_clean', ...
        'HD_AHV_model_results.mat');
end

requiredDirs = {cfg.DataProcessedDir, cfg.OutputsDir, cfg.ModelDataDir, ...
    cfg.SessionModelDataDir, cfg.ClassifiedCandidateDir, ...
    cfg.ModelFigureDir, cfg.ModelComparisonDir, ...
    cfg.AnatomyComparisonDir, cfg.PosterFigureDir, ...
    cfg.ClassComparisonDir};
for i = 1:numel(requiredDirs)
    if exist(requiredDirs{i}, 'dir') ~= 7
        mkdir(requiredDirs{i});
    end
end
end
